import type {
  AuditEntry,
  Client,
  CreditProduct,
  DocumentItem,
  Installment,
  Loan,
  LoanApplication,
  NotificationItem,
  Payment,
} from "./types";

export const products: CreditProduct[] = [
  {
    id: "prod-negocio",
    name: "Crédito Negócio",
    description:
      "Financiamento para reforço de capital de giro, stock e expansão de pequenos negócios.",
    minAmount: 50000,
    maxAmount: 2500000,
    minTerm: 3,
    maxTerm: 24,
    interestRate: 2.5,
    requirements: [
      "Documento de identificação válido",
      "Comprovativo de actividade",
      "Comprovativo de morada",
      "Extratos ou registo de vendas",
    ],
  },
  {
    id: "prod-pessoal",
    name: "Crédito Pessoal",
    description:
      "Solução ágil para necessidades pessoais urgentes, com análise transparente e prazos flexíveis.",
    minAmount: 25000,
    maxAmount: 750000,
    minTerm: 2,
    maxTerm: 18,
    interestRate: 2.8,
    requirements: [
      "Documento de identificação válido",
      "Comprovativo de rendimento",
      "Comprovativo de morada",
    ],
  },
  {
    id: "prod-agricola",
    name: "Crédito Agrícola",
    description:
      "Apoio a produtores e cooperativas para insumos, equipamentos e campanhas sazonais.",
    minAmount: 100000,
    maxAmount: 5000000,
    minTerm: 6,
    maxTerm: 36,
    interestRate: 2.2,
    requirements: [
      "Documento de identificação válido",
      "Comprovativo de exploração agrícola",
      "Plano de utilização do crédito",
    ],
  },
];

export const currentClient: Client = {
  id: "cli-001",
  name: "Maria Fernandes",
  email: "maria.fernandes@email.com",
  phone: "+258 84 123 4567",
  address: "Maputo, KaMpfumo",
  idDocument: "BI 010203040506M010",
  profession: "Comerciante",
  income: 450000,
  createdAt: "2026-01-12",
  status: "activo",
};

export const clients: Client[] = [
  currentClient,
  {
    id: "cli-002",
    name: "João Baptista",
    email: "joao.baptista@email.com",
    phone: "+258 86 222 3333",
    address: "Beira, Centro",
    idDocument: "BI 020304050607B012",
    profession: "Agricultor",
    income: 280000,
    createdAt: "2026-02-03",
    status: "pendente",
  },
  {
    id: "cli-003",
    name: "Ana Costa",
    email: "ana.costa@email.com",
    phone: "+258 85 444 5555",
    address: "Nampula, Centro",
    idDocument: "BI 030405060708N089",
    profession: "Costureira",
    income: 210000,
    createdAt: "2026-03-18",
    status: "activo",
  },
  {
    id: "cli-004",
    name: "Pedro Silva",
    email: "pedro.silva@email.com",
    phone: "+258 87 666 7777",
    address: "Matola, Machava",
    idDocument: "BI 040506070809T021",
    profession: "Motorista",
    income: 320000,
    createdAt: "2026-04-09",
    status: "activo",
  },
];

export const documents: DocumentItem[] = [
  {
    id: "doc-1",
    clientId: "cli-001",
    name: "Bilhete de Identidade",
    type: "Identificação",
    status: "aprovado",
    uploadedAt: "2026-01-12",
  },
  {
    id: "doc-2",
    clientId: "cli-001",
    name: "Comprovativo de Morada",
    type: "Morada",
    status: "aprovado",
    uploadedAt: "2026-01-12",
  },
  {
    id: "doc-3",
    clientId: "cli-001",
    name: "Extrato de Vendas",
    type: "Financeiro",
    status: "em_analise",
    uploadedAt: "2026-07-28",
  },
  {
    id: "doc-4",
    clientId: "cli-001",
    name: "Licença Comercial",
    type: "Profissional",
    status: "corrigir",
    uploadedAt: "2026-07-28",
    notes: "Documento ilegível. Envie uma cópia mais nítida.",
  },
  {
    id: "doc-5",
    clientId: "cli-002",
    name: "Bilhete de Identidade",
    type: "Identificação",
    status: "em_analise",
    uploadedAt: "2026-08-01",
  },
  {
    id: "doc-6",
    clientId: "cli-002",
    name: "Comprovativo Agrícola",
    type: "Profissional",
    status: "pendente",
    uploadedAt: "2026-08-01",
  },
];

export const applications: LoanApplication[] = [
  {
    id: "app-1",
    reference: "KUK-2026-0142",
    clientId: "cli-001",
    clientName: "Maria Fernandes",
    productId: "prod-negocio",
    productName: "Crédito Negócio",
    amount: 850000,
    term: 12,
    purpose: "Reforço de stock da loja",
    status: "em_analise",
    createdAt: "2026-08-05",
    updatedAt: "2026-08-08",
    monthlyPayment: 82145,
    totalPayable: 985740,
  },
  {
    id: "app-2",
    reference: "KUK-2026-0098",
    clientId: "cli-001",
    clientName: "Maria Fernandes",
    productId: "prod-pessoal",
    productName: "Crédito Pessoal",
    amount: 200000,
    term: 6,
    purpose: "Despesas familiares",
    status: "activo",
    createdAt: "2026-03-10",
    updatedAt: "2026-03-18",
    analyst: "Carla Mendes",
    monthlyPayment: 36800,
    totalPayable: 220800,
  },
  {
    id: "app-3",
    reference: "KUK-2026-0155",
    clientId: "cli-002",
    clientName: "João Baptista",
    productId: "prod-agricola",
    productName: "Crédito Agrícola",
    amount: 1200000,
    term: 18,
    purpose: "Compra de insumos",
    status: "info_adicional",
    createdAt: "2026-08-07",
    updatedAt: "2026-08-10",
    analyst: "Rui Almeida",
    decisionNote: "Falta plano de utilização do crédito.",
    monthlyPayment: 78400,
    totalPayable: 1411200,
  },
  {
    id: "app-4",
    reference: "KUK-2026-0160",
    clientId: "cli-003",
    clientName: "Ana Costa",
    productId: "prod-negocio",
    productName: "Crédito Negócio",
    amount: 450000,
    term: 9,
    purpose: "Aquisição de máquinas de costura",
    status: "aprovado",
    createdAt: "2026-08-02",
    updatedAt: "2026-08-11",
    analyst: "Carla Mendes",
    monthlyPayment: 55200,
    totalPayable: 496800,
  },
  {
    id: "app-5",
    reference: "KUK-2026-0130",
    clientId: "cli-004",
    clientName: "Pedro Silva",
    productId: "prod-pessoal",
    productName: "Crédito Pessoal",
    amount: 150000,
    term: 4,
    purpose: "Reparação de veículo",
    status: "desembolso_pendente",
    createdAt: "2026-07-20",
    updatedAt: "2026-08-09",
    analyst: "Rui Almeida",
    monthlyPayment: 41250,
    totalPayable: 165000,
  },
];

export const loans: Loan[] = [
  {
    id: "loan-1",
    applicationId: "app-2",
    reference: "KUK-2026-0098",
    clientId: "cli-001",
    clientName: "Maria Fernandes",
    principal: 200000,
    totalPayable: 220800,
    paidAmount: 147200,
    balance: 73600,
    term: 6,
    interestRate: 2.8,
    status: "activo",
    disbursedAt: "2026-03-18",
    nextDueDate: "2026-08-18",
    nextInstallment: 36800,
  },
  {
    id: "loan-2",
    applicationId: "app-x",
    reference: "KUK-2025-0881",
    clientId: "cli-003",
    clientName: "Ana Costa",
    principal: 300000,
    totalPayable: 345000,
    paidAmount: 230000,
    balance: 115000,
    term: 10,
    interestRate: 2.5,
    status: "em_atraso",
    disbursedAt: "2025-11-02",
    nextDueDate: "2026-07-28",
    nextInstallment: 34500,
  },
  {
    id: "loan-3",
    applicationId: "app-y",
    reference: "KUK-2025-0702",
    clientId: "cli-004",
    clientName: "Pedro Silva",
    principal: 180000,
    totalPayable: 198000,
    paidAmount: 198000,
    balance: 0,
    term: 6,
    interestRate: 2.8,
    status: "liquidado",
    disbursedAt: "2025-08-12",
    nextDueDate: "—",
    nextInstallment: 0,
  },
];

export const installments: Installment[] = [
  { id: "ins-1", loanId: "loan-1", number: 1, dueDate: "2026-04-18", amount: 36800, paidAmount: 36800, status: "pago", paidAt: "2026-04-17" },
  { id: "ins-2", loanId: "loan-1", number: 2, dueDate: "2026-05-18", amount: 36800, paidAmount: 36800, status: "pago", paidAt: "2026-05-16" },
  { id: "ins-3", loanId: "loan-1", number: 3, dueDate: "2026-06-18", amount: 36800, paidAmount: 36800, status: "pago", paidAt: "2026-06-18" },
  { id: "ins-4", loanId: "loan-1", number: 4, dueDate: "2026-07-18", amount: 36800, paidAmount: 36800, status: "pago", paidAt: "2026-07-15" },
  { id: "ins-5", loanId: "loan-1", number: 5, dueDate: "2026-08-18", amount: 36800, paidAmount: 0, status: "pendente" },
  { id: "ins-6", loanId: "loan-1", number: 6, dueDate: "2026-09-18", amount: 36800, paidAmount: 0, status: "pendente" },
];

export const payments: Payment[] = [
  {
    id: "pay-1",
    loanId: "loan-1",
    loanReference: "KUK-2026-0098",
    clientName: "Maria Fernandes",
    amount: 36800,
    method: "Transferência bancária",
    status: "confirmado",
    paidAt: "2026-07-15",
  },
  {
    id: "pay-2",
    loanId: "loan-1",
    loanReference: "KUK-2026-0098",
    clientName: "Maria Fernandes",
    amount: 36800,
    method: "Carteira móvel",
    status: "confirmado",
    paidAt: "2026-06-18",
  },
  {
    id: "pay-3",
    loanId: "loan-2",
    loanReference: "KUK-2025-0881",
    clientName: "Ana Costa",
    amount: 34500,
    method: "Carteira móvel",
    status: "pendente",
    paidAt: "2026-08-10",
  },
];

export const notifications: NotificationItem[] = [
  {
    id: "n1",
    type: "analise",
    title: "Pedido em análise",
    message: "O pedido KUK-2026-0142 está a ser analisado pela equipa de crédito.",
    createdAt: "2026-08-08T09:20:00",
    read: false,
  },
  {
    id: "n2",
    type: "lembrete",
    title: "Lembrete de prestação",
    message: "A prestação de 36.800 MT vence a 18/08/2026.",
    createdAt: "2026-08-11T08:00:00",
    read: false,
  },
  {
    id: "n3",
    type: "pagamento",
    title: "Pagamento confirmado",
    message: "Recebemos o pagamento de 36.800 MT referente ao empréstimo KUK-2026-0098.",
    createdAt: "2026-07-15T14:32:00",
    read: true,
  },
  {
    id: "n4",
    type: "pedido",
    title: "Pedido recebido",
    message: "O seu pedido KUK-2026-0142 foi registado com sucesso.",
    createdAt: "2026-08-05T11:05:00",
    read: true,
  },
];

export const auditLog: AuditEntry[] = [
  {
    id: "a1",
    action: "Aprovação de crédito",
    actor: "Carla Mendes",
    target: "KUK-2026-0160",
    createdAt: "2026-08-11T16:40:00",
    detail: "Pedido aprovado no valor de 450.000 MT",
  },
  {
    id: "a2",
    action: "Pedido de informação adicional",
    actor: "Rui Almeida",
    target: "KUK-2026-0155",
    createdAt: "2026-08-10T10:12:00",
    detail: "Solicitado plano de utilização do crédito",
  },
  {
    id: "a3",
    action: "Confirmação de desembolso",
    actor: "Sistema",
    target: "KUK-2026-0098",
    createdAt: "2026-03-18T09:00:00",
    detail: "Desembolso confirmado. Empréstimo activado.",
  },
];

export const adminStats = {
  carteiraActiva: 18450000,
  pedidosPendentes: 12,
  desembolsosMes: 4200000,
  taxaInadimplencia: 4.2,
  clientesActivos: 186,
  cobrancasAbertas: 9,
};

export const faqs = [
  {
    q: "Quem pode solicitar microcrédito?",
    a: "Qualquer pessoa singular ou pequeno negócio que cumpra os requisitos do produto escolhido e apresente a documentação exigida.",
  },
  {
    q: "Quanto tempo demora a análise?",
    a: "Após o envio completo dos documentos, a análise costuma ser concluída em poucos dias úteis, consoante a complexidade do pedido.",
  },
  {
    q: "Posso acompanhar o estado do pedido online?",
    a: "Sim. Na área do cliente visualiza o estado do pedido, documentos, contrato, desembolso e calendário de prestações.",
  },
  {
    q: "Como são feitos os pagamentos?",
    a: "A plataforma está preparada para integração com carteiras móveis, transferências bancárias e outros métodos definidos pela instituição.",
  },
];
